name: deploy no eks de exemplo usando self-hosted

on:
  push:
    branches:
    - master

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Install and configure kubectl
      run: |
        curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
        curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
        sudo chmod +x ./kubectl ./aws-iam-authenticator
        export PATH=$PWD/:$PATH
        sudo apt-get update && sudo apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli

    - name: Teste CLI
      run: |
        aws s3 ls

  